title: Sofia Sawczenko # your name (or website title) here 
logo: "https://github.com/sofiasawczenko/sofiasawczenko.github.io/blob/master/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br> Hello! Welcome to my Portfolio.
    <br><br>
    <i>“I am enough of an artist to draw freely upon my imagination. 
    Imagination is more important than knowledge. 
    Knowledge is limited. 
    Imagination encircles the world.”
    <b>― Albert Einstein</b></i>
    <br><br>
  <a href="https://www.linkedin.com/in/sofia-sawczenko/">View my LinkedIn Profile</a> 
  {% if site.github.is_user_page %}
        <p class="view"><a href="{{ site.github.owner_url }}">View My GitHub Profile</a></p>
        {% endif %}
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'

<footer>
        {% if site.github.is_project_page %}
        <p>This project is maintained by <a href="{{ site.github.owner_url }}">{{ site.github.owner_name }}</a></p>
        {% endif %}
        <p><small>Hosted on GitHub Pages</small></p>
</footer>
