title: Sofia Sawczenko # your name (or website title) here 
logo: "https://github.com/sofiasawczenko/sofiasawczenko.github.io/blob/master/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br> I'm a software engineering student well-versed in agile project management. My proficiency in Python, Complex Problem Solving, and leadership, coupled with strong analytical thinking, equips me to approach complex challenges with precision and efficiency. In casual settings, I'm known for effective communication; in formal environments, my strength lies in analytical thinking.
    <br><br>
    <i>“I am enough of an artist to draw freely upon my imagination. 
    Imagination is more important than knowledge. 
    Knowledge is limited. 
    Imagination encircles the world.”
    <b>― Albert Einstein</b></i>
    <br><br>
  <a href="https://www.linkedin.com/in/sofia-sawczenko/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
