title: Sofia Sawczenko # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
    My background in software engineering, along with extracurricular experience in project management supported by agile methodologies, allowed me to think holistically and analytically. Further, my professional experiences have provided me with lean problem-solving, Data Analysis, Machine Learning, and Python skills. In casual situations, I am known for my effective communication, while in more structured and formal circumstances, my strength lies in analytical thinking.
  <br><br>
    “I am enough of an artist to draw freely upon my imagination. 
    Imagination is more important than knowledge. 
    Knowledge is limited. 
    Imagination encircles the world.”
    ― Albert Einstein
  <br><br>
  <a href="https://www.linkedin.com/in/sofia-sawczenko/</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
